language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-ri --no-rdoc
  - gem install xcpretty --no-ri --no-rdoc
  - sudo easy_install cpp-coveralls
  - cd Tests
  - pod update
  - cd ..
script: rake test
after_success:
  - ./scripts/coveralls.sh
